[package]
name = "pmsim"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Porous media simulator"
homepage = "https://github.com/cpmech/pmsim"
repository = "https://github.com/cpmech/pmsim"
documentation = "https://docs.rs/pmsim"
readme = "README.md"
categories = ["mathematics", "science", "simulation"]
keywords = ["mechanics", "fem"]

[dependencies]
gemlab = "0.5"
plotpy = "0.4"
rayon = "1.7"
russell_chk = "0.5"
russell_lab = "0.5"
russell_sparse = "0.5"
russell_tensor = "0.5"
rmp-serde = "1.1"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
