[package]
name = "pmsim"
version = "0.3.0"
edition = "2021"
license = "MIT"
description = "Porous media simulator"
homepage = "https://github.com/cpmech/pmsim"
repository = "https://github.com/cpmech/pmsim"
documentation = "https://docs.rs/pmsim"
readme = "README.md"
categories = ["mathematics", "science", "simulation"]
keywords = ["mechanics", "fem"]

[features]
intel_mkl = [
    "russell_lab/intel_mkl",
    "russell_nonlin/intel_mkl",
    "russell_ode/intel_mkl",
    "russell_pde/intel_mkl",
    "russell_sparse/intel_mkl",
    "russell_stat/intel_mkl",
    "russell_tensor/intel_mkl",
]
local_sparse = [
    "russell_nonlin/local_sparse",
    "russell_ode/local_sparse",
    "russell_pde/local_sparse",
    "russell_sparse/local_sparse",
]
cudss = [
    "russell_nonlin/cudss",
    "russell_ode/cudss",
    "russell_pde/cudss",
    "russell_sparse/cudss",
]

[dependencies]
plotpy = "1.23"
gemlab = "2.4"
russell_lab = "2.8"
russell_nonlin = "2.8"
russell_ode = "2.8"
russell_pde = "2.8"
russell_sparse = "2.8"
russell_stat = "2.8"
russell_tensor = "2.8"
tritet = "3.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
uuid = { version = "1.24", features = ["v4"] }

[dev-dependencies]
serial_test = "3.5"
