[package]
name = "pmsim"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Porous media simulator"
homepage = "https://github.com/cpmech/pmsim"
repository = "https://github.com/cpmech/pmsim"
documentation = "https://docs.rs/pmsim"
readme = "README.md"
categories = ["mathematics", "science", "simulation"]
keywords = ["mechanics", "fem"]

[dependencies]
gemlab = { path = "../gemlab", version = "0.4" }
plotpy = { path = "../plotpy", version = "0.3" }
rayon = "1.5"
russell_chk = { path = "../russell/russell_chk", version = "0.4" }
russell_lab = { path = "../russell/russell_lab", version = "0.4" }
russell_sparse = { path = "../russell/russell_sparse", version = "0.4" }
russell_tensor = { path = "../russell/russell_tensor", version = "0.4" }
rmp-serde = "1.1"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
