[package]
name = "pmsim"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Porous media simulator"
homepage = "https://github.com/cpmech/pmsim"
repository = "https://github.com/cpmech/pmsim"
documentation = "https://docs.rs/pmsim"
readme = "README.md"
categories = ["mathematics", "science", "simulation"]
keywords = ["mechanics", "fem"]

[dependencies]
gemlab = { path = "../gemlab", version = "0.4" }
plotpy = "0.3"
russell_chk = "0.4"
russell_lab = "0.4"
russell_sparse = "0.4"
russell_tensor = "0.4"
rmp-serde = "1.0.0"
serde = { version = "1.0.136", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.78"
