//! Implements the finite element method

mod bc_concentrated;
mod bc_distributed;
mod bc_prescribed;
mod control_loader;
mod control_residual;
mod control_stepper;
mod element_diffusion;
mod element_rod;
mod element_rod_gnl;
mod element_solid;
mod element_trait;
mod elements;
mod fem_results;
mod fem_state;
mod linear_system;
mod logger;
mod paraview;
mod post_processing;
mod secondary_values;
mod solver_common;
mod solver_new;
mod solver_old;
mod stats;

pub use bc_concentrated::*;
pub use bc_distributed::*;
use bc_prescribed::*;
use control_loader::*;
use control_residual::*;
use control_stepper::*;
pub use element_diffusion::*;
pub use element_rod::*;
pub use element_rod_gnl::*;
pub use element_solid::*;
pub use element_trait::*;
pub use elements::*;
pub use fem_results::*;
pub use fem_state::*;
use linear_system::*;
use logger::*;
use paraview::*;
pub use post_processing::*;
pub use secondary_values::*;
use solver_common::*;
pub use solver_new::*;
pub use solver_old::*;
use stats::*;
